koji-target-prefix: pulp-2.8
rsync-target-dir: 2.8/stage
rsync-tested-dir: 2.8/dev
repositories:
  - name: pulp
    external_deps: deps/external_deps.json
    git_url: git@github.com:pulp/pulp.git
    git_branch: pulp-2.8.5-0.1.beta
    version: 2.8.5-1
  - name: pulp_puppet
    git_url: git@github.com:pulp/pulp_puppet.git
    git_branch: pulp-puppet-2.8.5-0.1.beta
    version: 2.8.5-1
  - name: pulp_rpm
    git_url: git@github.com:pulp/pulp_rpm.git
    git_branch: pulp-rpm-2.8.5-0.1.beta
    version: 2.8.5-1
# 0.1.beta was a broken release due to the 2.8.4 hotfix
# 0.2.beta was good, but we added a new commit after building
# 0.3.beta is legit!
  - name: pulp_docker
    git_url: git@github.com:pulp/pulp_docker.git
    git_branch: pulp-docker-2.0.2-0.3.beta
    version: 2.0.2-1
  - name: crane
    git_url: git@github.com:pulp/crane.git
    git_branch: python-crane-2.0.1-0.1.beta
    version: 2.0.1-1
  - name: pulp_ostree
    git_url: git@github.com:pulp/pulp_ostree.git
    git_branch: pulp-ostree-1.1.2-0.1.beta
    version: 1.1.2-1
# at 0.2.beta due to a change added after 0.1.beta,
# but before the release was announced (similar to docker 0.3.beta)
  - name: pulp_python
    git_url: git@github.com:pulp/pulp_python.git
    git_branch: pulp-python-1.1.2-0.2.beta
    version: 1.1.2-1
