koji-target-prefix: pulp-2.8
rsync-target-dir: 2.8/stage
rsync-tested-dir: 2.8/dev
repositories:
  - name: pulp
    external_deps: deps/external_deps.json
    git_url: git@github.com:pulp/pulp.git
    git_branch: 2.8-release
    version: 2.8.5-1
  - name: pulp_puppet
    git_url: git@github.com:pulp/pulp_puppet.git
    git_branch: 2.8-release
    version: 2.8.5-1
  - name: pulp_rpm
    git_url: git@github.com:pulp/pulp_rpm.git
    git_branch: 2.8-release
    version: 2.8.5-1
  - name: pulp_docker
    git_url: git@github.com:pulp/pulp_docker.git
    git_branch: 2.0-release
    version: 2.0.2-1
  - name: crane
    git_url: git@github.com:pulp/crane.git
    git_branch: 2.0-release
    version: 2.0.1-1
  - name: pulp_ostree
    git_url: git@github.com:pulp/pulp_ostree.git
    git_branch: 1.1-release
    version: 1.1.2-1
  - name: pulp_python
    git_url: git@github.com:pulp/pulp_python.git
    git_branch: 1.1-release
    version: 1.1.2-1
